#!/usr/bin/env ruby

PROXIED_SERVICE_GROUPS = [
  "📱 TikTok", "🤖 OpenAI", "🧠 Claude", "💎 Google AI", "🧑‍💻 GitHub Copilot",
  "🪟 Microsoft Copilot", "🖱️ Cursor", "🔍 Perplexity", "𝕏 xAI / Grok",
  "🤗 Hugging Face", "🏄 Windsurf", "🧠 JetBrains AI"
].freeze
MAINLAND_DIRECT_GROUPS = [
  "🖥️ Microsoft Services", "🎮 Gaming Platforms", "📽️ Emby", "🐟 Fallback Routing"
].freeze

# Keep routing rules in one source; publish two complete location profiles.
def location_profiles(root)
  base = File.read(File.join(root, "shadowrocket.conf"))
  {
    "mainland-china" => ["Mainland China", "dns-mainland-china"],
    "hong-kong" => ["Hong Kong", "privacy-dns"]
  }.to_h do |slug, (label, dns_module)|
    body = base.sub(/\A.*?\[General\]/m,
      "# #{label}. Nodes and subscriptions stay outside this repository.\n" \
      "# Generated by scripts/generate_profiles.rb; edit shadowrocket.conf, rules, and modules instead.\n" \
      "# DNS is included. Disable DNS modules when switching location profiles.\n\n[General]")
    dns = File.read(File.join(root, "modules/#{dns_module}.module")).split("[General]\n", 2).fetch(1).strip
    body.sub!("[General]\n", "[General]\n#{dns}\n")
    body.sub!(%r{(?<=update-url = )[^\n]+},
      "https://raw.githubusercontent.com/hongkongkiwi/shadowrocket-vpn-configs/main/#{slug}.conf")
    # Both locations use narrow AI/TikTok rules instead of shared-service matches.
    body = body.lines.reject { |line| line.match?(%r{^RULE-SET,.*/(?:Claude|Gemini|TikTok)\.list,}) }.join
    narrow_rules = File.read(File.join(root, "rules/hong-kong-proxy.list"))
    body.sub!("[Rule]\n", "[Rule]\n#{narrow_rules}\n")
    if slug == "mainland-china"
      body.gsub!(/^(.*) = select,([^\n]+)/) do
        name, fields = Regexp.last_match(1), Regexp.last_match(2).split(",")
        default = MAINLAND_DIRECT_GROUPS.include?(name) ? "DIRECT" : "PROXY"
        "#{name} = select,#{default},#{fields.reject { |field| field == default }.join(',')}"
      end
      body = body.lines.reject { |line| line.match?(%r{^RULE-SET,.*/(?:CDN|Proxy)\.list,}) }.join
      # A saved fallback selector must not turn unmatched traffic into a proxy route.
      body.sub!("FINAL,🐟 Fallback Routing", "FINAL,DIRECT")
      mainland_rules = File.read(File.join(root, "rules/mainland-china.list"))
      body.sub!("[Rule]\n", "[Rule]\n#{mainland_rules}\n")
      # Domestic domain matches precede broad service lists without forcing early IP resolution.
      china_domains = body.lines.find { |line| line.start_with?("DOMAIN-SET,") && line.include?("/ChinaMax/") }
      body.sub!(china_domains, "")
      body.sub!("// --- Services ---", "#{china_domains}// --- Services ---")
    else
      # Choose by service, independently of the source profile's candidate order.
      body.gsub!(/^(.*) = select,([^\n]+)/) do
        name, fields = Regexp.last_match(1), Regexp.last_match(2).split(",")
        default = PROXIED_SERVICE_GROUPS.include?(name) ? "PROXY" : "DIRECT"
        "#{name} = select,#{default},#{fields.reject { |field| field == default }.join(',')}"
      end
    end
    ["#{slug}.conf", body]
  end
end

if $PROGRAM_NAME == __FILE__
  root = File.expand_path("..", __dir__)
  location_profiles(root).each do |filename, body|
    File.write(File.join(root, filename), body)
    puts "Generated #{filename}"
  end
end
