#!/usr/bin/env ruby

# Keep routing rules in one source; publish two complete location profiles.
def location_profiles(root)
  base = File.read(File.join(root, "shadowrocket.conf"))
  {
    "mainland-china" => ["Mainland China", "dns-mainland-china"],
    "hong-kong" => ["Hong Kong", "privacy-dns"]
  }.to_h do |slug, (label, dns_module)|
    body = base.sub(/\A.*?\[General\]/m,
      "# #{label}. Nodes and subscriptions stay outside this repository.\n" \
      "# Generated by scripts/generate_profiles.rb; edit shadowrocket.conf, rules, and modules instead.\n" \
      "# DNS is included. Disable DNS modules when switching location profiles.\n\n[General]")
    dns = File.read(File.join(root, "modules/#{dns_module}.module")).split("[General]\n", 2).fetch(1).strip
    body.sub!("[General]\n", "[General]\n#{dns}\n")
    body.sub!(%r{(?<=update-url = )[^\n]+},
      "https://raw.githubusercontent.com/hongkongkiwi/shadowrocket-vpn-configs/main/#{slug}.conf")
    if slug == "hong-kong"
      # AI and TikTok already start with the US group; all other selectors use PROXY.
      body.gsub!(/^(.* = select,)(PROXY,[^\n]+)/) do
        prefix, fields = Regexp.last_match(1), Regexp.last_match(2).split(",")
        "#{prefix}DIRECT,#{fields.reject { |field| field == 'DIRECT' }.join(',')}"
      end
      # The upstream lists include shared services and whole-network matches.
      body = body.lines.reject { |line| line.match?(%r{^RULE-SET,.*/(?:Claude|Gemini|TikTok)\.list,}) }.join
      narrow_rules = File.read(File.join(root, "rules/hong-kong-proxy.list"))
      body.sub!("[Rule]\n", "[Rule]\n#{narrow_rules}\n")
    end
    ["#{slug}.conf", body]
  end
end

if $PROGRAM_NAME == __FILE__
  root = File.expand_path("..", __dir__)
  location_profiles(root).each do |filename, body|
    File.write(File.join(root, filename), body)
    puts "Generated #{filename}"
  end
end
